# Generated by Django 5.0 on 2023-12-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=64)),
                ("password", models.CharField(max_length=64)),
                (
                    "profilepic",
                    models.ImageField(
                        default="static/portal/profilepics/default.png",
                        upload_to="static/portal/profilepics/",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="interests", to="portal.topics"
                    ),
                ),
            ],
        ),
    ]
