# Generated by Django 5.0 on 2024-01-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="interested_topics",
            field=models.ManyToManyField(
                blank=True, related_name="interested_users", to="portal.topic"
            ),
        ),
    ]
