# Generated by Django 5.0 on 2023-12-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilepic",
            field=models.ImageField(
                blank=True,
                default="static/portal/profilepics/default.png",
                null=True,
                upload_to="static/portal/profilepics/",
            ),
        ),
    ]
