# Generated by Django 5.0 on 2023-12-31 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_alter_user_profilepic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topics",
            new_name="Topic",
        ),
    ]
