# Generated by Django 5.0 on 2024-01-05 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_topic_user_interested_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilepic",
            field=models.ImageField(
                default="media/portal/profilepics/default.png",
                upload_to="media/portal/profilepics/",
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        default="covers/default.png",
                        null=True,
                        upload_to="covers/",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "listed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="books", to="portal.topic"
                    ),
                ),
            ],
        ),
    ]
