# Generated by Django 5.0 on 2024-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_user_profilepic_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilepic",
            field=models.ImageField(
                default="profilepics/default.png", upload_to="profilepics/"
            ),
        ),
    ]
