# Generated by Django 5.0 on 2023-12-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_alter_user_groups_alter_user_profilepic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
