# Generated by Django 5.0 on 2023-12-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_topic_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="interests", to="portal.topic"
            ),
        ),
    ]
