# Generated by Django 5.0 on 2023-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_alter_user_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="interests", to="portal.topic"
            ),
        ),
    ]
