# Generated by Django 5.0 on 2023-12-31 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_alter_user_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.AddField(
            model_name="topic",
            name="interested_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
