# Generated by Django 5.0 on 2023-12-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_remove_user_interests_topic_interested_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
