# Generated by Django 5.0 on 2023-12-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
